import { MenuItemDataTypes } from 'services/menus/types';

const headerMenuDummy: MenuItemDataTypes[] = [
  {
    id: 1,
    menuId: 1,
    depth: 1,
    lft: 1,
    parentId: 1,
    referenceId: 1,
    reference: {
      slug: '/',
    },
    type: '22',
    createdAt: 'ss',
    target: '_blank',
    rgt: 1,
    title: 'Trang chủ',
    updatedAt: 'sss',
  },
  {
    id: 1,
    menuId: 1,
    depth: 1,
    lft: 1,
    parentId: 1,
    referenceId: 1,
    reference: {
      slug: '/ve-chung-toi',
    },
    type: '22',
    createdAt: 'ss',
    target: '_blank',
    rgt: 1,
    title: 'giới thiệu',
    updatedAt: 'sss',
  },
  {
    id: 1,
    menuId: 1,
    depth: 1,
    lft: 1,
    parentId: 1,
    referenceId: 1,
    reference: {
      slug: '/linh-vuc-hoat-dong',
    },
    type: '22',
    createdAt: 'ss',
    target: '_blank',
    rgt: 1,
    title: 'Lĩnh vực hoạt động',
    updatedAt: 'sss',
  },
  {
    id: 1,
    menuId: 1,
    depth: 1,
    lft: 1,
    parentId: 1,
    referenceId: 1,
    reference: {
      slug: '/quan-he-dau-tu',
    },
    type: '22',
    createdAt: 'ss',
    target: '_blank',
    rgt: 1,
    title: 'quan hệ đầu tư',
    updatedAt: 'sss',
  },
  {
    id: 1,
    menuId: 1,
    depth: 1,
    lft: 1,
    parentId: 1,
    referenceId: 1,
    reference: {
      slug: '/tin-tuc',
    },
    type: '22',
    createdAt: 'ss',
    target: '_blank',
    rgt: 1,
    title: 'tin tức',
    updatedAt: 'sss',
  },
  {
    id: 1,
    menuId: 1,
    depth: 1,
    lft: 1,
    parentId: 1,
    referenceId: 1,
    reference: {
      slug: '/tuyen-dung',
    },
    type: '22',
    createdAt: 'ss',
    target: '_blank',
    rgt: 1,
    title: 'tuyển dụng',
    updatedAt: 'sss',
  },
  {
    id: 1,
    menuId: 1,
    depth: 1,
    lft: 1,
    parentId: 1,
    referenceId: 1,
    reference: {
      slug: '/lien-he',
    },
    type: '22',
    createdAt: 'ss',
    target: '_blank',
    rgt: 1,
    title: 'liên hệ',
    updatedAt: 'sss',
  },
];

export const headerRecruitmentMenuDummy: MenuItemDataTypes[] = [
  {
    id: 1,
    menuId: 1,
    depth: 1,
    lft: 1,
    parentId: 1,
    referenceId: 1,
    reference: {
      slug: '/tuyen-dung',
    },
    type: '22',
    createdAt: 'ss',
    target: '_blank',
    rgt: 1,
    title: 'Novaland Tuyển dụng',
    updatedAt: 'sss',
  },
  {
    id: 1,
    menuId: 1,
    depth: 1,
    lft: 1,
    parentId: 1,
    referenceId: 1,
    reference: {
      slug: '/moi-truong-lam-viec',
    },
    type: '22',
    createdAt: 'ss',
    target: '_blank',
    rgt: 1,
    title: 'Môi trường làm việc',
    updatedAt: 'sss',
  },
  {
    id: 1,
    menuId: 1,
    depth: 1,
    lft: 1,
    parentId: 1,
    referenceId: 1,
    reference: {
      slug: '/co-hoi-nghe-nghiep',
    },
    type: '22',
    createdAt: 'ss',
    target: '_blank',
    rgt: 1,
    title: 'Cơ hội nghề nghiệp',
    updatedAt: 'sss',
  },
];

export const headerSustainableDevelopmentMenuDummy: MenuItemDataTypes[] = [
  {
    id: 1,
    menuId: 1,
    depth: 1,
    lft: 1,
    parentId: 1,
    referenceId: 1,
    reference: {
      slug: '/hoi-dong-phat-trien-ben-vung',
    },
    type: '22',
    createdAt: 'ss',
    target: '_blank',
    rgt: 1,
    title: 'Hội Đồng Phát Triển Bền Vững',
    updatedAt: 'sss',
  },
  {
    id: 11,
    menuId: 1,
    depth: 1,
    lft: 1,
    parentId: 1,
    referenceId: 1,
    reference: {
      slug: '/quan-tri-tap-doan',
    },
    type: '22',
    createdAt: 'ss',
    target: '_blank',
    rgt: 1,
    title: 'Quản Trị Tập Đoàn',
    subMenu: [
      {
        id: 12,
        menuId: 1,
        depth: 2,
        lft: 1,
        parentId: 11,
        referenceId: 1,
        reference: {
          slug: '/quan-tri-tap-doan',
        },
        type: '22',
        createdAt: 'ss',
        target: '_blank',
        rgt: 1,
        title: 'Định vị sản phẩm phân khúc trung và cao cấp',
        updatedAt: 'sss',
      },
      {
        id: 14,
        menuId: 1,
        depth: 2,
        lft: 1,
        parentId: 11,
        referenceId: 1,
        reference: {
          slug: '/quan-tri-tap-doan',
        },
        type: '22',
        createdAt: 'ss',
        target: '_blank',
        rgt: 1,
        title: 'Tiếp thị và truyền thông',
        updatedAt: 'sss',
      },
      {
        id: 14,
        menuId: 1,
        depth: 2,
        lft: 1,
        parentId: 11,
        referenceId: 1,
        reference: {
          slug: '/quan-tri-tap-doan',
        },
        type: '22',
        createdAt: 'ss',
        target: '_blank',
        rgt: 1,
        title: 'Dịch vụ khách hàng với tư duy “khách hàng là số 1”',
        updatedAt: 'sss',
      },
      {
        id: 14,
        menuId: 1,
        depth: 2,
        lft: 1,
        parentId: 11,
        referenceId: 1,
        reference: {
          slug: '/quan-tri-tap-doan',
        },
        type: '22',
        createdAt: 'ss',
        target: '_blank',
        rgt: 1,
        title: 'Dịch vụ hậu mãi Novaloyalty - chương trình chăm sóc khách hàng',
        updatedAt: 'sss',
      },
    ],
    updatedAt: 'sss',
  },
  {
    id: 1,
    menuId: 1,
    depth: 1,
    lft: 1,
    parentId: 1,
    referenceId: 1,
    reference: {
      slug: '/quan-tri-nguon-nhan-luc',
    },
    type: '22',
    createdAt: 'ss',
    target: '_blank',
    rgt: 1,
    title: 'Quản Trị Nguồn Nhân Lực',
    updatedAt: 'sss',
  },
  {
    id: 1,
    menuId: 1,
    depth: 1,
    lft: 1,
    parentId: 1,
    referenceId: 1,
    reference: {
      slug: '/quan-tri-thuong-hieu',
    },
    type: '22',
    createdAt: 'ss',
    target: '_blank',
    rgt: 1,
    title: 'Quản Trị Thương Hiệu',
    updatedAt: 'sss',
  },
  {
    id: 1,
    menuId: 1,
    depth: 1,
    lft: 1,
    parentId: 1,
    referenceId: 1,
    reference: {
      slug: '/moi-truong',
    },
    type: '22',
    createdAt: 'ss',
    target: '_blank',
    rgt: 1,
    title: 'Môi Trường',
    updatedAt: 'sss',
  },
  {
    id: 1,
    menuId: 1,
    depth: 1,
    lft: 1,
    parentId: 1,
    referenceId: 1,
    reference: {
      slug: '/thong-diep-novaland',
    },
    type: '22',
    createdAt: 'ss',
    target: '_blank',
    rgt: 1,
    title: 'Thông Điệp Novaland',
    updatedAt: 'sss',
  },
];

export type LanguageType = 'VN'|'EN';

export const LIST_LANGUAGE:Array<{label:LanguageType, value: string}> = [
  {
    label: 'VN',
    value: 'vi',
  },
  {
    label: 'EN',
    value: 'en',
  },
];

export default headerMenuDummy;
